receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048
  memory_limiter:
    # 80% of maximum memory up to 512M for local development
    limit_mib: 200
    # 25% of limit
    spike_limit_mib: 50
    check_interval: 5s

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

exporters:
  clickhouse:
    endpoint: tcp://${env:INIT_DB_HOST}:${env:INIT_DB_PORT}?dial_timeout=10s
    database: ${env:INIT_DB_DATABASE}
    username: ${env:INIT_DB_USERNAME}
    password: ${env:INIT_DB_PASSWORD}
    ttl: 24h  # Shorter retention for local development
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
  # Optional: Log to console for debugging
  logging:
    loglevel: info

service:
  extensions: [zpages]
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse]
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888
